#name: Maven CI
#
#on:
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master
#
#jobs:
#  build-and-publish:
#    runs-on: ubuntu-latest
#
#    permissions:
#      packages: write
#      contents: read
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up JDK
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#
#      - name: Install Maven
#        run: sudo apt-get update && sudo apt-get install -y maven
#
#      - name: Configure Maven settings
#        run: |
#          mkdir -p ~/.m2
#          echo "<settings>
#                  <servers>
#                    <server>
#                      <id>github</id>
#                      <username>${{ github.actor }}</username>
#                      <password>${{ secrets.GITHUB_TOKEN }}</password>
#                    </server>
#                  </servers>
#                </settings>" > ~/.m2/settings.xml
#
#      - name: Build with Maven (skip tests)
#        run: mvn -B clean package -DskipTests -Dmaven.test.skip=true --file pom.xml
#
#      - name: Clear local Maven repository
#        run: rm -rf ~/.m2/repository/com/sentifraud/
#
#      - name: Publish to GitHub Packages
#        run: mvn deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Upload build artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: build-artifacts
#          path: target/*.jar

name: Maven CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write # Required to push to gh-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.GITHUB_TOKEN }}</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml

      - name: Build with Maven (skip tests)
        run: mvn -B clean package -DskipTests -Dmaven.test.skip=true --file pom.xml

      - name: Clear local Maven repository
        run: rm -rf ~/.m2/repository/com/sentifraud/

      - name: Publish to GitHub Packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: target/*.jar

      - name: Generate Javadocs
        run: mvn javadoc:javadoc

      - name: Deploy Javadocs to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Create a temporary directory for the gh-pages branch
          mkdir -p gh-pages

          # Copy the generated Javadocs to the gh-pages directory
          cp -r target/site/apidocs/* gh-pages/

          # Checkout the gh-pages branch
          git fetch origin gh-pages || true
          git checkout -b gh-pages origin/gh-pages || git checkout --orphan gh-pages

          # Remove existing files (except .git)
          git rm -rf . || true

          # Add the new Javadocs
          cp -r gh-pages/* .
          git add .

          # Commit and push the changes
          git commit -m "Deploy Javadocs for ${{ github.sha }}"
          git push origin gh-pages