name: Maven CI

on:
  push:
    branches:
      - master  # Trigger on push to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull requests targeting the master branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up JDK
        uses: actions/setup-java@v4  # Updated to v4
        with:
          java-version: '17'  # Specify the Java version
          distribution: 'temurin'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven  # Ensure Maven is installed

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Publish to GitHub Packages
        run: mvn deploy -s settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: build-artifacts
          path: target/*.jar
