name: Maven CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'  # Specify the Java version you are using
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Publish to GitHub Packages
        run: |
          mvn deploy -s settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optional: Upload build artifacts (e.g., JAR files) as workflow artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/*.jar